### PR TITLE
Mocking tests

### PR DESCRIPTION
**Pull request by Dextroz**
Hey @momozor 

I have made some tests using real JSON return data from the Pixabay API.

I have used Pytest and I use black as the linter.

Currently I have added two methods of testing. Up to you which one you think is best.

This is not related to my bug issue. This addresses #4 

Thanks,
Dex.

### CODE REVIEW

**Comment by momozor** [comment]
Thanks :+1:  :smile:

**Comment by Dextroz** [comment]
Oops sorry. I wasn’t anticipating you would merge so quickly! 😅

I should have said. In the tests, I proposed two ways of doing the tests and wanted you to choose. I assumed you would see this, I should have put this in the original message.

**Comment by momozor** [comment]
Thanks for pointing that out. I updated it at the commit 0105143

**Comment by Dextroz** [comment]
Great! Glad I could be of some help! 😃👍🏻

**Comment by momozor** [comment]
Good work! :)

**Pull request merged**
